name: ihcl-cms

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "build"
    jobs:
      - job: BuildPush
        steps:
          - bash: |
              short_hash=$(git rev-parse --short=7 HEAD)
              echo "##vso[task.setvariable variable=short_hash]$short_hash"
            displayName: Set Docker Image Tag
          - publish: $(Pipeline.Workspace)
            artifact: variables
            displayName: Publish Docker Image Tag Artifact

  - stage: dev-deploy
    displayName: Deploy to DEV
    jobs:
      - deployment: DeployToDev
        environment: 'ihcl-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: variables
                - bash: |
                    short_hash=$(cat $(Pipeline.Workspace)/variables/short_hash)
                    echo "##vso[task.setvariable variable=short_hash]$short_hash"
                  displayName: Get Docker Image Tag

              
