name: ihcl-cms
trigger:
- master
- uat

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "git-hash"
    jobs:
      - job: BuildPush
        steps:
          - bash: |
             short_hash=`git rev-parse --short=7 HEAD`
             mkdir -p $(Pipeline.Workspace)/variables
             echo "$short_hash" > $(Pipeline.Workspace)/variables/short_hash
             echo "##vso[task.setvariable variable=short_hash]$short_hash" 

          - publish: $(Pipeline.Workspace)/variables
            artifact: variables
            displayName: Publish Docker Image Tag
  - stage:  "dev-deploy"
    displayName: Deploy to DEV
    jobs:
     - deployment: ""
       variables:
       - group: DevVariableGroup


    
