name: ihcl-cms

trigger:
  branches:
    include:
      - refs/heads/master
      - refs/heads/CICD-PT
      - refs/heads/CICD-E2E

pool:
  vmImage: ubuntu-latest
variables:
- group: DevVariableGroup
- group: SitVariableGroup
- name: ihclwebsites
  value: 'ihclwebsites.azurecr.io'

stages:
  - stage: "build"
    jobs:
      - job: BuildImageTag
        steps:
          - bash: |  

              short_hash=`git rev-parse --short=7 HEAD`
              mkdir -p $(Pipeline.Workspace)/variables
              echo "$short_hash" > $(Pipeline.Workspace)/variables/short_hash
              echo "##vso[task.setvariable variable=short_hash]$short_hash" 
              echo "short hash value ===$short_hash"
            displayName: Set Docker Image Tag
          - publish: $(Pipeline.Workspace)/variables
            artifact: variables
            displayName: Publish Docker Image Tag Artifact

  - stage: dev_deploy
    dependsOn:
    - Build
    displayName: Deploy to DEV
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: DeployToDev
        variables:
          - group: DevVariableGroup
        environment: 'ihcl-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: variables
                - bash: |
                    short_hash=$(cat $(Pipeline.Workspace)/variables/short_hash)
                    echo "##vso[task.setvariable variable=short_hash]$short_hash"
                    echo "short hash ==${short_hash}"
                  displayName: Get Docker Image Tag

                - bash: |
                    az login --service-principal --username $(Service_Principle_Name) --password $(Service_Priniciple_Password) --tenant $(Tenant_ID)
                    az acr build --image dev/ihcl-cms:$(short_hash) --registry ihclwebsites --file Dockerfile .
                    az aks get-credentials --resource-group Websites_Dev --name app-dev-aks
                  displayName: Login to ACR and AKS
                  enabled: true
                  
                - bash: |
                    helm upgrade --install ihcl-cms --set-string image.tag=$(short_hash) --namespace dev --create-namespace -f ./charts/ihcl-cms/values/values-dev.yaml --wait ./charts/ihcl-cms
                  displayName: Helm Upgrade
                  condition: succeeded()
  - stage: pt_deploy
    dependsOn:
    - Build
    displayName: Deploy to PT
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/CICD-PT'))
    jobs:
      - deployment: DeployToPT
        variables:
          - group: PtVariableGroup
        environment: 'ihcl-pt'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: variables
                - bash: |
                    short_hash=$(cat $(Pipeline.Workspace)/variables/short_hash)
                    echo "##vso[task.setvariable variable=short_hash]$short_hash"
                    echo "short hash ==${short_hash}"
                  displayName: Get Docker Image Tag

                - bash: |
                    az login --service-principal --username $(Service_Principle_Name) --password $(Service_Priniciple_Password) --tenant $(Tenant_ID)
                    az acr build --image pt/ihcl-cms:$(short_hash) --registry ihclwebsites --file Dockerfile .
                    az aks get-credentials --resource-group Website_PT_RG --name app-PT-aks
                  displayName: Login to ACR and AKS
                  enabled: true
                - bash: |
                    helm upgrade --install ihcl-cms --set-string image.tag=$(short_hash) --namespace pt --create-namespace -f ./charts/ihcl-cms/values/values-pt.yaml --wait ./charts/ihcl-cms
                  displayName: Helm Upgrade 
  - stage: e2e_deploy
    dependsOn:
    - Build
    displayName: Deploy to E2E
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/CICD-E2E'))
    jobs:
      - deployment: DeployToE2E
        variables:
          - group: e2eVariableGroup
        environment: 'ihcl-e2e'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: variables
                - bash: |
                    short_hash=$(cat $(Pipeline.Workspace)/variables/short_hash)
                    echo "##vso[task.setvariable variable=short_hash]$short_hash"
                    echo "short hash ==${short_hash}"
                  displayName: Get Docker Image Tag

                - bash: |
                    az login --service-principal --username $(Service_Principle_Name) --password $(Service_Priniciple_Password) --tenant $(Tenant_ID)
                    az acr build --image e2e/ihcl-cms:$(short_hash) --registry ihclwebsites --file Dockerfile .
                    az aks get-credentials --resource-group Website_E2E_RG --name app-E2E-aks
                  displayName: Login to ACR and AKS
                  enabled: true
                - bash: |
                    helm upgrade --install ihcl-cms --set-string image.tag=$(short_hash) --namespace e2e --create-namespace -f ./charts/ihcl-cms/values/values-e2e.yaml --wait ./charts/ihcl-cms
                  displayName: Helm Upgrade                   
                  