name: ihcl-cms

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest
variables:
- group: DevVariableGroup
- group: SitVariableGroup
- name: ihclwebsites
  value: 'ihclwebsites.azurecr.io'

stages:
  - stage: "build"
    jobs:
      - job: BuildPush
        steps:
          - bash: |
              short_hash=$(git rev-parse --short=7 HEAD)
              echo "##vso[task.setvariable variable=short_hash]$short_hash"
            displayName: Set Docker Image Tag
          - publish: $(Pipeline.Workspace)
            artifact: variables
            displayName: Publish Docker Image Tag Artifact

  - stage: dev_deploy
    displayName: Deploy to DEV
    jobs:
      - deployment: DeployToDev
        variables:
          - group: DevVariableGroup
        environment: 'ihcl-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: variables
                - bash: |
                    short_hash=$(cat $(Pipeline.Workspace)/variables/short_hash)
                    echo "##vso[task.setvariable variable=short_hash]$short_hash"
                  displayName: Get Docker Image Tag

                - bash: |
                    az login --service-principal --username $(Service_Principle_Name) --password $(Service_Priniciple_Password) --tenant $(Tenant_ID)
                    az acr build --image dev/ihcl-cms:$(short_hash) --registry ihclwebsites --file Dockerfile .
                    az aks get-credentials --resource-group Websites_Dev --name app-dev-aks
                  displayName: Login to ACR and AKS
                  enabled: true
                - bash: |
                    helm upgrade --install ihcl-cms --set-string image.tag=$(short_hash) --namespace dev --create-namespace -f ./charts/ihcl-cms/values/values-dev.yaml --wait ./charts/ihcl-cms
                  displayName: Helm Upgrade
