name: ihcl-cms
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "build"
    jobs:
      - job: BuildPush
        steps:
          - bash: |
             short_hash=`git rev-parse --short=7 HEAD`
             mkdir -p $(Pipeline.Workspace)/variables
             echo "$short_hash" > $(Pipeline.Workspace)/variables/short_hash
             echo "##vso[task.setvariable variable=short_hash]$short_hash" 

          - publish: $(Pipeline.Workspace)/variables
            artifact: variables
            displayName: Publish Docker Image Tag
  - stage:  dev-deploy
    displayName: Deploy to DEV
    jobs:
     - deployment: Deploy to DEV
       variables:
       - group: DevVariableGroup
       environment: 'ihcl-dev'
       strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - download: current
                artifact: varible
              - bash: |
                 pwd
                 ls -ltr
                displayName: "Print for debug"
              - bash: |
                  short_hash=$(cat $(Pipeline.Workspace)/variables/short_hash)
                  echo "##vso[task.setvariable variable=short_hash]$short_hash"
                displayName: Get Docker ImageTag
              - bash: |
                  az login --service-principal --username $(Service_Principle_Name) --password $(Service_Priniciple_Password) --tenant $(Tenant_ID)
                  az acr build --image dev/ihcl-web:$(short_hash) --registry ihclwebsites --file Dockerfile .
                  az aks get-credentials --resource-group Websites_Dev --name app-dev-aks
                displayName: Login to DEV AKS and Build
              - bash: |
                  helm upgrade --install ihcl-cms --set-string image.tag=$(short_hash) --namespace dev --create-namespace -f ./charts/ihcl-cms/values/values-dev.yaml --wait ./charts/ihcl-cms
                  workingDirectory: $(System.DefaultWorkingDirectory)
                displayName: Helm Upgrade
             




    
